# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import projeto_DSID_pb2 as projeto__DSID__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ChamadaVoid = channel.unary_unary(
        '/helloworld.Greeter/ChamadaVoid',
        request_serializer=projeto__DSID__pb2.RequestVoid.SerializeToString,
        response_deserializer=projeto__DSID__pb2.ReplyVoid.FromString,
        )
    self.ChamadaLong = channel.unary_unary(
        '/helloworld.Greeter/ChamadaLong',
        request_serializer=projeto__DSID__pb2.RequestLong.SerializeToString,
        response_deserializer=projeto__DSID__pb2.ReplyLong.FromString,
        )
    self.Chamada8Long = channel.unary_unary(
        '/helloworld.Greeter/Chamada8Long',
        request_serializer=projeto__DSID__pb2.Request8Long.SerializeToString,
        response_deserializer=projeto__DSID__pb2.ReplyLong.FromString,
        )
    self.ChamadaString = channel.unary_unary(
        '/helloworld.Greeter/ChamadaString',
        request_serializer=projeto__DSID__pb2.RequestString.SerializeToString,
        response_deserializer=projeto__DSID__pb2.ReplyString.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def ChamadaVoid(self, request, context):
    """Chamada sem argumentos e sem valor de retorno
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChamadaLong(self, request, context):
    """Chamada com argumento long e retorno long  
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Chamada8Long(self, request, context):
    """Chamada com 8 argumentos long e retorno long
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChamadaString(self, request, context):
    """Chamada com argumento string e retorno string
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ChamadaVoid': grpc.unary_unary_rpc_method_handler(
          servicer.ChamadaVoid,
          request_deserializer=projeto__DSID__pb2.RequestVoid.FromString,
          response_serializer=projeto__DSID__pb2.ReplyVoid.SerializeToString,
      ),
      'ChamadaLong': grpc.unary_unary_rpc_method_handler(
          servicer.ChamadaLong,
          request_deserializer=projeto__DSID__pb2.RequestLong.FromString,
          response_serializer=projeto__DSID__pb2.ReplyLong.SerializeToString,
      ),
      'Chamada8Long': grpc.unary_unary_rpc_method_handler(
          servicer.Chamada8Long,
          request_deserializer=projeto__DSID__pb2.Request8Long.FromString,
          response_serializer=projeto__DSID__pb2.ReplyLong.SerializeToString,
      ),
      'ChamadaString': grpc.unary_unary_rpc_method_handler(
          servicer.ChamadaString,
          request_deserializer=projeto__DSID__pb2.RequestString.FromString,
          response_serializer=projeto__DSID__pb2.ReplyString.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
