# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projeto_DSID.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='projeto_DSID.proto',
  package='helloworld',
  syntax='proto3',
  serialized_pb=_b('\n\x12projeto_DSID.proto\x12\nhelloworld\"\r\n\x0bRequestVoid\"\x0b\n\tReplyVoid\"\x1a\n\x0bRequestLong\x12\x0b\n\x03num\x18\x01 \x01(\x03\"\x1c\n\tReplyLong\x12\x0f\n\x07message\x18\x01 \x01(\x03\"~\n\x0cRequest8Long\x12\x0c\n\x04num1\x18\x08 \x01(\x03\x12\x0c\n\x04num2\x18\x01 \x01(\x03\x12\x0c\n\x04num3\x18\x02 \x01(\x03\x12\x0c\n\x04num4\x18\x03 \x01(\x03\x12\x0c\n\x04num5\x18\x04 \x01(\x03\x12\x0c\n\x04num6\x18\x05 \x01(\x03\x12\x0c\n\x04num7\x18\x06 \x01(\x03\x12\x0c\n\x04num8\x18\x07 \x01(\x03\"\x1d\n\rRequestString\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bReplyString\x12\x0f\n\x07message\x18\x01 \x01(\t2\x95\x02\n\x07Greeter\x12?\n\x0b\x43hamadaVoid\x12\x17.helloworld.RequestVoid\x1a\x15.helloworld.ReplyVoid\"\x00\x12?\n\x0b\x43hamadaLong\x12\x17.helloworld.RequestLong\x1a\x15.helloworld.ReplyLong\"\x00\x12\x41\n\x0c\x43hamada8Long\x12\x18.helloworld.Request8Long\x1a\x15.helloworld.ReplyLong\"\x00\x12\x45\n\rChamadaString\x12\x19.helloworld.RequestString\x1a\x17.helloworld.ReplyString\"\x00\x42\x31\n\x14io.grpc.projeto-DSIDB\x10ProjetoDSIDProtoP\x01\xa2\x02\x04\x44SIDb\x06proto3')
)




_REQUESTVOID = _descriptor.Descriptor(
  name='RequestVoid',
  full_name='helloworld.RequestVoid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=47,
)


_REPLYVOID = _descriptor.Descriptor(
  name='ReplyVoid',
  full_name='helloworld.ReplyVoid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=60,
)


_REQUESTLONG = _descriptor.Descriptor(
  name='RequestLong',
  full_name='helloworld.RequestLong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='helloworld.RequestLong.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=88,
)


_REPLYLONG = _descriptor.Descriptor(
  name='ReplyLong',
  full_name='helloworld.ReplyLong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.ReplyLong.message', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=118,
)


_REQUEST8LONG = _descriptor.Descriptor(
  name='Request8Long',
  full_name='helloworld.Request8Long',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='helloworld.Request8Long.num1', index=0,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='helloworld.Request8Long.num2', index=1,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num3', full_name='helloworld.Request8Long.num3', index=2,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num4', full_name='helloworld.Request8Long.num4', index=3,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num5', full_name='helloworld.Request8Long.num5', index=4,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num6', full_name='helloworld.Request8Long.num6', index=5,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num7', full_name='helloworld.Request8Long.num7', index=6,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num8', full_name='helloworld.Request8Long.num8', index=7,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=246,
)


_REQUESTSTRING = _descriptor.Descriptor(
  name='RequestString',
  full_name='helloworld.RequestString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.RequestString.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=277,
)


_REPLYSTRING = _descriptor.Descriptor(
  name='ReplyString',
  full_name='helloworld.ReplyString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.ReplyString.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=309,
)

DESCRIPTOR.message_types_by_name['RequestVoid'] = _REQUESTVOID
DESCRIPTOR.message_types_by_name['ReplyVoid'] = _REPLYVOID
DESCRIPTOR.message_types_by_name['RequestLong'] = _REQUESTLONG
DESCRIPTOR.message_types_by_name['ReplyLong'] = _REPLYLONG
DESCRIPTOR.message_types_by_name['Request8Long'] = _REQUEST8LONG
DESCRIPTOR.message_types_by_name['RequestString'] = _REQUESTSTRING
DESCRIPTOR.message_types_by_name['ReplyString'] = _REPLYSTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestVoid = _reflection.GeneratedProtocolMessageType('RequestVoid', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTVOID,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RequestVoid)
  ))
_sym_db.RegisterMessage(RequestVoid)

ReplyVoid = _reflection.GeneratedProtocolMessageType('ReplyVoid', (_message.Message,), dict(
  DESCRIPTOR = _REPLYVOID,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ReplyVoid)
  ))
_sym_db.RegisterMessage(ReplyVoid)

RequestLong = _reflection.GeneratedProtocolMessageType('RequestLong', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTLONG,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RequestLong)
  ))
_sym_db.RegisterMessage(RequestLong)

ReplyLong = _reflection.GeneratedProtocolMessageType('ReplyLong', (_message.Message,), dict(
  DESCRIPTOR = _REPLYLONG,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ReplyLong)
  ))
_sym_db.RegisterMessage(ReplyLong)

Request8Long = _reflection.GeneratedProtocolMessageType('Request8Long', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST8LONG,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Request8Long)
  ))
_sym_db.RegisterMessage(Request8Long)

RequestString = _reflection.GeneratedProtocolMessageType('RequestString', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTSTRING,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RequestString)
  ))
_sym_db.RegisterMessage(RequestString)

ReplyString = _reflection.GeneratedProtocolMessageType('ReplyString', (_message.Message,), dict(
  DESCRIPTOR = _REPLYSTRING,
  __module__ = 'projeto_DSID_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ReplyString)
  ))
_sym_db.RegisterMessage(ReplyString)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024io.grpc.projeto-DSIDB\020ProjetoDSIDProtoP\001\242\002\004DSID'))

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=312,
  serialized_end=589,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChamadaVoid',
    full_name='helloworld.Greeter.ChamadaVoid',
    index=0,
    containing_service=None,
    input_type=_REQUESTVOID,
    output_type=_REPLYVOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChamadaLong',
    full_name='helloworld.Greeter.ChamadaLong',
    index=1,
    containing_service=None,
    input_type=_REQUESTLONG,
    output_type=_REPLYLONG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Chamada8Long',
    full_name='helloworld.Greeter.Chamada8Long',
    index=2,
    containing_service=None,
    input_type=_REQUEST8LONG,
    output_type=_REPLYLONG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChamadaString',
    full_name='helloworld.Greeter.ChamadaString',
    index=3,
    containing_service=None,
    input_type=_REQUESTSTRING,
    output_type=_REPLYSTRING,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
